### PR TITLE
Dyson dev

### PR DESCRIPTION
**Pull request by mb354**
Hi,
I have been working on improving the GTS program so it tracks automatically after clicking ONLY ONCE  ( there were many bugs on that feature). The bugs fixed are:
- To transit execute lossrecovery when it doesnt track
- Removed some asserts that were causing trouble
- Takes into account the orientation of the robot when creating a patch for tracking the target
- Corrected m_pos when lost near the limits of the window due to offsets. Otherwise it get in a state where ncc2 returns 0 and lossRecovery never recovers 
- To speedup the lossrecovery it computes cross correlation only on pixels divisible by 2.

Also, there are some improvements on the instructions for installing and fixed another crash when postprocessing.  

Let me know if you have any question regarding those commits. Also, I have code to work with Ethernet cameras, the problem was caused because the uniqueID - DevicePath property was blank so it couldn't match any camera. The proposed solution would be to use the camera name as uniqueID if its blank, so it preserves compatibility.

### CODE REVIEW

**Comment by akramhussein** [comment]
RE: Ethernet Cameras

I understand the issue you've seen - had it with some USB cameras. What kind of support are you seeing for the cameras as I do not have one to test. Does it work fine with the GTS? Multiple cameras ok?

Akram

**Comment by mb354** [comment]
I already added support for ethernet cameras on another branch for my use ( dev-new) . I didn't test with USB cameras.

I had to add two things to the code:
- Use the camera Name if the UniqueId is empty
- And did the demosaicing of the camera inside UpdateQImage function (I couldn't find a way to keep compatibility with other cameras for that modification)

I will correct the typo so those improvements can be added to your project.

**Comment by akramhussein** [comment]
Hi Marc,

I've tested the changes and they seem fine. If you can just make the correction to the install instructions I'll merge it in. Thanks for addressing these issues.

Thanks,
Akram

**Comment by mb354** [comment]
I just corrected the typo and some minor things in the instructions. This pull request should include a commit from June 23rd (4763d06). I guess if that commit is included we are good to go.

Cheers

**Pull request merged**
